name: mongo CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      # uses: superchargejs/mongodb-github-action@v1
      uses: ./
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install
    - run: npm test
      env:
        CI: true
