name: mongo CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        mongodb-version: [4.2]

    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: mongo port
      run: echo ${PORT}
      env:
        PORT: ${{ job.services.mongodb.ports['27017'] }}

    - run: npm install
    - run: npm test
      env:
        CI: true
